# Generated by Django 5.2.11 on 2026-02-14 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behavior', '0003_alter_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deriv_login_id', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('real', 'Real'), ('demo', 'Demo')], max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('encrypted_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='deriv_accounts', to='behavior.userprofile')),
            ],
            options={
                'db_table': 'deriv_accounts',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'deriv_login_id')},
            },
        ),
    ]
