# Generated by Django 5.2.11 on 2026-02-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0002_userprofile_email_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
